package dev.kxrim;

public class Main {
    static void main() {
        HtmlBuilder htmlBuilder = new HtmlBuilder();
        htmlBuilder.setLang("en");
        htmlBuilder.setCharset("UTF-8");
        htmlBuilder.setTitle("My First HTML Document");
        htmlBuilder.addElement("h1", "Hello, World!");
        htmlBuilder.addElement("p", "This is a sample HTML document generated by HtmlBuilder.");
        htmlBuilder.build();
    }
}
